--nauczyciele
INSERT INTO users (user_login, user_name, user_last, user_pass, user_mail, user_date, user_level) VALUES
    ('nauczyciel1',  'Tomasz',    'Drewniak',     sha1('pralka88'), 't.drewniak@gmail.com',      NOW(), 2),
    ('nauczyciel2',  'Maria',     'Mikler',       sha1('pralka88'), 'm.mikler@gmail.com',        NOW(), 2),
    ('nauczyciel3',  'Barbara',   'Lacna',        sha1('pralka88'), 'b.lacna@gmail.com',         NOW(), 2),
    ('nauczyciel4',  'Genowefa',  'Lisewska',     sha1('pralka88'), 'g.lisewska@gmail.com',      NOW(), 2),
    ('nauczyciel5',  'Dorota',    'Foltan',       sha1('pralka88'), 'd.foltan@gmail.com',        NOW(), 2),
    ('nauczyciel6',  'Eliza',     'Szary',        sha1('pralka88'), 'e.szary@gmail.com',         NOW(), 2),
    ('nauczyciel7',  'Magdalena', 'Wisla',        sha1('pralka88'), 'm.wisla@gmail.com',         NOW(), 2),
    ('nauczyciel8',  'Krystyna',  'Iwanska',      sha1('pralka88'), 'k.iwanska@gmail.com',       NOW(), 2),
    ('nauczyciel9',  'Danuta',    'Danek',        sha1('pralka88'), 'd.danek@gmail.com',         NOW(), 2),
    ('nauczyciel10', 'Andrzej',   'Sadlok',       sha1('pralka88'), 'a.sadlok@gmail.com',        NOW(), 2),
    ('nauczyciel11', 'Zdzislaw',  'Chmielarczyk', sha1('pralka88'), 'z.chimielarczyk@gmail.com', NOW(), 2),
    ('nauczyciel12', 'Boleslaw',  'Blaszczak',    sha1('pralka88'), 'b.blaszack@gmail.com',      NOW(), 2),
    ('nauczyciel13', 'Boleslaw',  'Blaszczak',    sha1('pralka88'), 'b.blaszack@gmail.com',      NOW(), 2),
    ('nauczyciel14', 'Iwona',     'Handzlik',     sha1('pralka88'), 'i.hanzlik@gmail.com',       NOW(), 2),
    ('nauczyciel15', 'Zofia',     'Bieronska',    sha1('pralka88'), 'z.bieronska@gmail.com',     NOW(), 2),
    ('nauczyciel16', 'Agnieszka', 'Slosarczyk',   sha1('pralka88'), 'z.slosarczyk@gmail.com',    NOW(), 2),
    ('nauczyciel17', 'Krzstyna',  'Tora',         sha1('pralka88'), 'k.tora@gmail.com',          NOW(), 2),
    ('nauczyciel18', 'Bozena',    'Motyka',       sha1('pralka88'), 'b.motyka@gmail.com',        NOW(), 2),
    ('nauczyciel19', 'Anna',      'Markiel',      sha1('pralka88'), 'a.markiel@gmail.com',       NOW(), 2),
    ('nauczyciel20', 'Marzena',   'Nycz',         sha1('pralka88'), 'a.nycz@gmail.com',          NOW(), 2),
    ('nauczyciel21', 'Piotr',     'Blaszczak',    sha1('pralka88'), 'p.blaszack@gmail.com',      NOW(), 2),
    ('nauczyciel22', 'Agnieszka', 'Berezowska',   sha1('pralka88'), 'a.berezowska@gmail.com',    NOW(), 2);

--klasy
INSERT INTO categories (cat_name, cat_desc, cat_by) VALUES
    ('Klasa 1A', 'wychowawca: Tomasz Drewniak',   1),
    ('Klasa 1B', 'wychowawca: Maria Mikler',      2),
    ('Klasa 1C', 'wychowawca: Barbara Lacna',     3),
    ('Klasa 2A', 'wychowawca: Genowefa Lisewska', 4),
    ('Klasa 2B', 'wychowawca: Dorota Foltan',     5),
    ('Klasa 2C', 'wychowawca: Eliza Szary',       6),
    ('Klasa 3A', 'wychowawca: Magdalena Wisla',   7),
    ('Klasa 3B', 'wychowawca: Krystyna Iwanska',  8),
    ('Klasa 3C', 'wychowawca: Danuta Danek',      9);

INSERT INTO classes (cat_id) VALUES
    (1), (2), (3), (4), (5), (6), (7), (8), (9);

INSERT INTO users (user_login, user_name, user_last, user_mail, user_pass, user_date, user_level) VALUES
('uczen1',  'Przedwoj',     'Imanow',       'p.imanow@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen2',  'Borzymir',     'Zabryszewska', 'b.zabryszewska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen3',  'Paulin',       'Sokolan',      'p.sokolan@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen4',  'Anatol',       'Reszczanska',  'a.reszczanska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen5',  'Odyseusz',     'Reckwald',     'o.reckwald@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen6',  'Wolmar',       'Szoski',       'w.szoski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen7',  'Zachariasz',   'Wijas',        'z.wijas@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen8',  'Kanty',        'Bucierka',     'k.bucierka@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen9',  'Milorad',      'Kimczuk',      'm.kimczuk@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen10', 'Lucjusz',      'Holoniecki',   'l.holoniecki@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen11', 'Dymitriusz',   'Procaj',       'd.procaj@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen12', 'Donat',        'Kazimienna',   'd.kazimienna@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen13', 'Lucjusz',      'Macewicz',     'l.macewicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen14', 'Jaczewoj',     'Nasinski',     'j.nasinski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen15', 'Fides',        'Cermann',      'f.cermann@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen16', 'Demetriusz',   'Stief',        'd.stief@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen17', 'Emeryk',       'Kowgier',      'e.kowgier@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen18', 'Porfirion',    'Pieciulewicz', 'p.pieciulewicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen19', 'Dobrogniew',   'Kehlo',        'd.kehlo@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen20', 'Cieszygor',    'Marneniuk',    'c.marneniuk@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen21', 'Przybyslaw',   'Piorecki',     'p.piorecki@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen22', 'Czcislaw',     'Milas',        'c.milas@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen23', 'Izaak',        'Gawlenski',    'i.gawlenski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen24', 'Dobiemir',     'Polocznik',    'd.polocznik@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen25', 'Cyrus',        'Knoester',     'c.knoester@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen26', 'Odil',         'Franciewicz',  'o.franciewicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen27', 'Bogdan',       'Damratowski',  'b.damratowski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen28', 'Warcislaw',    'Akimowicz',    'w.akimowicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen29', 'Renat',        'Zwierz',       'r.zwierz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen30', 'Wirgiliusz',   'Leloszkiewi',  'w.leloszkiewi@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen31', 'Dlugosz',      'Drosdeck',     'd.drosdeck@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen32', 'Longin',       'Kociubiak',    'l.kociubiak@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen33', 'Melchior',     'Grochonska',   'm.grochonska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen34', 'Zbigniew',     'Reznerska',    'z.reznerska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen35', 'Goscimil',     'Wiktarski',    'g.wiktarski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen36', 'Spycimir',     'Siodmak',      's.siodmak@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen37', 'Arkadiusz',    'Jednaszczyk',  'a.jednaszczyk@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen38', 'Janusz',       'Ciechaniak',   'j.ciechaniak@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen39', 'Herkulan',     'Wywialkowski', 'h.wywialkowski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen40', 'Kanut',        'Lersz',        'k.lersz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen41', 'Tezeusz',      'Urbanellis',   't.urbanellis@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen42', 'Klet',         'Kratofil',     'k.kratofil@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen43', 'Przedpelk',    'Kojscarz',     'p.kojscarz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen44', 'Patrycjusz',   'Rappke',       'p.rappke@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen45', 'Hiacynt',      'Namyslok',     'h.namyslok@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen46', 'Niedamir',     'Szczurzynski', 'n.szczurzynski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen47', 'Humbert',      'Juliano',      'h.juliano@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen48', 'Siemowit',     'Cypranska',    's.cypranska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen49', 'Dobromil',     'Szymanczyki',  'd.szymanczykie@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen50', 'Dobromir',     'Tatysiak',     'd.tatysiak@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen51', 'Karp',         'Mojczek',      'k.mojczek@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen52', 'Olaf',         'Morel',        'o.morel@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen53', 'Mokij',        'Planer',       'm.planer@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen54', 'Borys',        'Kodzis',       'b.kodzis@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen55', 'Benignus',     'Przedzienko',  'b.przedzienkow@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen56', 'Roderyk',      'Tywuszyk',     'r.tywuszyk@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen57', 'Eberhard',     'Szmaida',      'e.szmaida@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen58', 'Artemon',      'Brozek',       'a.brozek@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen59', 'Wawrzyniec',   'Czajarek',     'w.czajarek@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen60', 'Niezamysl',    'Plewik',       'n.plewik@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen61', 'Ewaryst',      'Siery',        'e.siery@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen62', 'Sedzislaw',    'Ludwin',       's.ludwin@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen63', 'Dobrogniew',   'Aresztowicz',  'd.aresztowicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen64', 'Patrycjusz',   'Lewun',        'p.lewun@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen65', 'Boleslaw',     'Ruslakow',     'b.ruslakow@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen66', 'Probus',       'Schuermer',    'p.schuermer@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen67', 'Aureliusz',    'Mezynski',     'a.mezynski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen68', 'Czcislaw',     'Chmurzewski',  'c.chmurzewski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen69', 'Florencjusz',  'Benagorska',   'f.benagorska@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen70', 'Ludomil',      'Czabania',     'l.czabania@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen71', 'Sylwery',      'Niesbecka',    's.niesbecka@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen72', 'Dytrych',      'Bociarn',      'd.bociarn@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen73', 'Korneliusz',   'Pomeranz',     'k.pomeranz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen74', 'Martynin',     'Jentsek',      'm.jentsek@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen75', 'Przedwoj',     'Kiempczynski', 'p.kiempczynski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen76', 'Borzyslaw',    'Zersz',        'b.zersz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen77', 'Wszegniew',    'Miktaszewicz', 'w.miktaszewicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen78', 'Gabin',        'Wypusc',       'g.wypusc@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen79', 'Kwiryn',       'Efinowicz',    'k.efinowicz@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen80', 'Dobromil',     'Psich',        'd.psich@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen81', 'Dobroslaw',    'Turyk',        'd.turyk@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen82', 'Swiecimir',    'Sasowski',     's.sasowski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen83', 'Rafael',       'Charlos',      'r.charlos@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen84', 'Polikarp',     'Lyznik',       'p.lyznik@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen85', 'Jozefat',      'Efemberek',    'j.efenberg@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen86', 'Eulogiusz',    'Powiecki',     'e.powiecki@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen87', 'Filemon',      'Trzasowski',   'f.trzasowski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen88', 'Dobromir',     'Warczakowski', 'd.warczakowski@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen89', 'Ezechiel',     'Jullian',      'e.jullian@gmail.com',	sha1('pralka88'), NOW(), 0),
('uczen90', 'Wojbor',       'Osorio',       'w.osorio@gmail.com',	sha1('pralka88'), NOW(), 0);

--students
INSERT INTO students (user_id, class_id) VALUES
    (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), 
    (33, 2), (34, 2), (35, 2), (36, 2), (37, 2), (38, 2), (39, 2), (40, 2), (41, 2), (42, 2),
    (43, 3), (44, 3), (45, 3), (46, 3), (47, 3), (48, 3), (49, 3), (50, 3), (51, 3), (52, 3),
    (53, 4), (54, 4), (55, 4), (56, 4), (57, 4), (58, 4), (59, 4), (60, 4), (61, 4), (62, 4),
    (63, 5), (64, 5), (65, 5), (66, 5), (67, 5), (68, 5), (69, 5), (70, 5), (71, 5), (72, 5),
    (73, 6), (74, 6), (75, 6), (76, 6), (77, 6), (78, 6), (79, 6), (80, 6), (81, 6), (82, 6),
    (83, 7), (84, 7), (85, 7), (86, 7), (87, 7), (88, 7), (89, 7), (90, 7), (91, 7), (92, 7),
    (93, 8), (94, 8), (95, 8), (96, 8), (97, 8), (98, 8), (99, 8), (100, 8),(101, 8),(102, 8),
    (103, 9), (104, 9), (105, 9), (106, 9), (107, 9), (108, 9), (109, 9), (110, 9), (111, 9), (112, 9);

--children
    --3x
    INSERT into children (child_1, child_2, child_3) VALUES
        (23, 33, 43), (24, 34, 44), (25, 35, 45), (26, 36, 46), (27, 37, 47), (28, 38, 48),
        (29, 39, 49), (30, 40, 50), (31, 41, 51), (32, 42, 52), (53, 58, 63), (54, 59, 64),
        (55, 60, 65), (56, 61, 66), (57, 62, 67);
    --2x
    INSERT into children (child_1, child_2) VALUES
        (68, 83), (69, 84), (70, 85), (71, 86), (72, 87), 
        (73, 88), (74, 89), (75, 90), (76, 91), (77, 92),
        (78, 93), (79, 94), (80, 95), (81, 96), (82, 97);
    --1x
    INSERT into children (child_1) VALUES
        (98),  (99), (100), (101), (102),
        (103), (104), (105), (106), (107),
        (108), (109), (110), (111), (112);

--rodzice
INSERT INTO users (user_login, user_name, user_last, user_mail, user_pass, user_date, user_level) VALUES
    ('rodzic1',  'Lukasz',	'Imanow',	'l.imanow@gmail.com',       sha1('pralka88'), NOW(), 1),
    ('rodzic2',  'Oliwier',	'Zabryszewska',	'o.zabryszewska@gmail.com', sha1('pralka88'), NOW(), 1),
    ('rodzic3',  'Galezy',	'Sokolan',	'g.sokolan@gmail.com',      sha1('pralka88'), NOW(), 1),
    ('rodzic4',  'Sofroniusz',	'Reszczanska',	's.reszczanska@gmail.com',  sha1('pralka88'), NOW(), 1),
    ('rodzic5',  'Daroslaw',	'Reckwald',	'd.reckwald@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic6',  'Kain',        'Szoski',	'k.szoski@gmail.com',       sha1('pralka88'), NOW(), 1),
    ('rodzic7',  'Krystian',	'Wijas',	'k.wijas@gmail.com',        sha1('pralka88'), NOW(), 1),
    ('rodzic8',  'Ambrozy',	'Bucierka',	'a.bucierka@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic9',  'Prosper',	'Kimczuk',	'p.kimczuk@gmail.com',      sha1('pralka88'), NOW(), 1),
    ('rodzic10', 'Gerard',	'Holoniecki',	'g.holoniecki@gmail.com',   sha1('pralka88'), NOW(), 1),
    ('rodzic11', 'Wszeciech',	'Procaj',	'w.procaj@gmail.com',       sha1('pralka88'), NOW(), 1),
    ('rodzic12', 'Dragomir',	'Kazimienna',	'd.kazimienna@gmail.com',   sha1('pralka88'), NOW(), 1),
    ('rodzic13', 'Alan',	'Macewicz',	'a.macewicz@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic14', 'Sambor',	'Nasinski',	's.nasinski@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic15', 'Kain',	'Cermann',	'k.cermann@gmail.com',      sha1('pralka88'), NOW(), 1),
    ('rodzic16', 'Stojmir',	'Stief',	's.stief@gmail.com',        sha1('pralka88'), NOW(), 1),
    ('rodzic17', 'Bazyl',	'Kowgier',	'b.kowgier@gmail.com',      sha1('pralka88'), NOW(), 1),
    ('rodzic18', 'Kalistrat',	'Pieciulewicz',	'k.pieciulewicz@gmail.com', sha1('pralka88'), NOW(), 1),
    ('rodzic19', 'Bartlomiej',	'Kehlo',	'b.kehlo@gmail.com',        sha1('pralka88'), NOW(), 1),
    ('rodzic20', 'Aleksy',	'Marneniuk',	'a.marneniuk@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic21', 'Zygmunt',	'Piorecki',	'z.piorecki@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic22', 'Modest',	'Milas',	'm.milas@gmail.com',        sha1('pralka88'), NOW(), 1),
    ('rodzic23', 'Maksymin',	'Gawlenski',	'm.gawlenski@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic24', 'Uniewit',	'Polocznik',	'u.polocznik@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic25', 'Spycislaw',	'Knoester',	's.knoester@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic26', 'Kanut',	'Franciewicz',	'k.franciewicz@gmail.com',  sha1('pralka88'), NOW(), 1),
    ('rodzic27', 'Mokij',	'Damratowski',	'm.damratowski@gmail.com',  sha1('pralka88'), NOW(), 1),
    ('rodzic28', 'Eligiusz',	'Akimowicz',	'e.akimowicz@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic29', 'Zefir',	'Zwierz',	'z.zwierz@gmail.com',       sha1('pralka88'), NOW(), 1),
    ('rodzic30', 'Strzezymir',	'Leloszkiewic',	's.leloszkiewic@gmail.com', sha1('pralka88'), NOW(), 1),
    ('rodzic31', 'Odil',	'Drosdeck',	'o.drosdeck@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic32', 'Wawrzyniec',	'Kociubiak',	'w.kociubiak@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic33', 'Fryderyk',	'Grochonska',	'f.grochonska@gmail.com',   sha1('pralka88'), NOW(), 1),
    ('rodzic34', 'Marian',	'Reznerska',	'm.reznerska@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic35', 'Tezeusz',	'Wiktarski',	't.wiktarski@gmail.com',    sha1('pralka88'), NOW(), 1),
    ('rodzic36', 'Daniel',	'Siodmak',	'd.siodmak@gmail.com',      sha1('pralka88'), NOW(), 1),
    ('rodzic37', 'Niemir',	'Jednaszczyk',	'n.jednaszczyk@gmail.com',  sha1('pralka88'), NOW(), 1),
    ('rodzic38', 'Bertram',	'Ciechaniak',	'b.ciechaniak@gmail.com',   sha1('pralka88'), NOW(), 1),
    ('rodzic39', 'Jaropelk',	'Wywialkowski',	'j.wywialkowski@gmail.com', sha1('pralka88'), NOW(), 1),
    ('rodzic40', 'Gedeon',	'Lersz',	'g.lersz@gmail.com',        sha1('pralka88'), NOW(), 1),
    ('rodzic41', 'Stojslaw',	'Urbanellis',	's.urbanellis@gmail.com',   sha1('pralka88'), NOW(), 1),
    ('rodzic42', 'Przybymir',	'Kratofil',	'p.kratofil@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic43', 'Domarad',	'Kojscarz',	'd.kojscarz@gmail.com',     sha1('pralka88'), NOW(), 1),
    ('rodzic44', 'Sewerian',	'Rappke',	's.rappke@gmail.com',       sha1('pralka88'), NOW(), 1),
    ('rodzic45', 'Tomislaw',	'Namyslok',	't.namyslok@gmail.com',     sha1('pralka88'), NOW(), 1);

INSERT INTO parents (user_id, children_id) VALUES
    (113, 1),  (114, 2),  (115, 3),  (116, 4),  (117, 5),
    (118, 6),  (119, 7),  (120, 8),  (121, 9),  (122, 10),
    (123, 11), (124, 12), (125, 13), (126, 14), (127, 15),
    (128, 16), (129, 17), (130, 18), (131, 19), (132, 20),
    (133, 21), (134, 22), (135, 23), (136, 24), (137, 25),
    (138, 26), (139, 27), (140, 28), (141, 29), (142, 30),
    (143, 31), (144, 32), (145, 33), (146, 34), (147, 35),
    (148, 36), (149, 37), (150, 38), (151, 39), (152, 40),
    (153, 41), (154, 42), (155, 43), (156, 44), (157, 45);